/* EN overlay — achievements. Stesse chiavi di js/data/achievements.js. */
window.gameData = window.gameData || {};
window.gameData.i18n = window.gameData.i18n || {};
window.gameData.i18n.en = window.gameData.i18n.en || {};
window.gameData.i18n.en.achievements = {
    primoClick: { desc: "Land your first manual click.", flavor: "The first bug is always the easiest one." },
    primoTeam: { desc: "Own 10 QA Assistants." },
    jiraWarrior: { desc: "Handle 25 Jira Tickets." },
    clickMaster: { desc: "Reach 10,000 manual clicks." },
    codeMonkey: { desc: "Rack up 50,000 total bugs." },
    automationFirst: { desc: "Reach 10 QA Teams." },
    clickGod: { desc: "Reach 2,000 manual clicks." },
    clickDictator: { name: "Mouse Dictator", desc: "Reach 20,000 manual clicks." },
    middleManagement: { desc: "Hire 100 QA Assistants." },
    fullStack: { desc: "Own at least 1 unit of every Team." },
    milionario: { desc: "Rack up 10 Million bugs." },
    geishaUnlock: { desc: "Play for 4 hours total." },
    miliardario: { desc: "Rack up 1 Billion bugs." },
    errore404: { desc: "Meet the Blue Screen of Death." },
    hacker: { desc: "Buy the Ethical Hacking upgrade." },
    waifuUnlock: { desc: "Own 100 AI Debuggers." },
    divinitaMouse: { name: "Mouse Deity", desc: "Buy the \"Divine Click\" upgrade." },
    natale: { name: "Merry Christmas", desc: "A special gift just for you!", flavor: "At Christmas we're all a little nicer (except the bugs)." },
    madeInHeaven: { desc: "Reboot the universe for the first time.", flavor: "Time accelerates toward a new beginning." },
    timeLord: { name: "Time Lord", desc: "Perform 5 system Reformats.", flavor: "You've seen the end and the beginning one too many times." },
    coscienzaEspansa: { name: "Expanded Consciousness", desc: "Own 1 Conscious Singularity." },
    dioCodice: { name: "God of Code", desc: "Own 100 Infinity Architectures." },
    theAnswer: { name: "The Answer to Everything", desc: "Land 42 manual clicks.", flavor: "Forty-two. The Question, however, remains unknown." },
    over9000: { name: "It's Over 9000!", desc: "Exceed 9,000 Bugs per second (BPS).", flavor: "WHAT?! NINE THOUSAND?!" },
    leetHaxor: { desc: "Reach 1,337 manual clicks.", flavor: "You're officially elite. 0wn3d." },
    shinyHunter: { name: "Shiny!", desc: "Click your first Golden Bug.", flavor: "The odds? Negligible. The glory? Eternal." },
    comboBreaker: { desc: "Reach a 50-click combo.", flavor: "A metallic voice screams in the distance." },
    esposionUnlock: { name: "Esposion!", desc: "Reach a 150-click combo.", flavor: "Keep the rhythm until Espo can't take the pressure." },
    doge: { desc: "Rack up 1 Million total bugs.", flavor: "wow. very click. so debug. much bug." },
    stonks: { desc: "Rack up 100 Million total bugs.", flavor: "↗ Only up. Don't ask how." },
    gottaGoFast: { desc: "Exceed 1,000 Bugs per second (BPS).", flavor: "A blue hedgehog nods in approval." },
    shutUpTakeMoney: { name: "Shut Up and Take My Money!", desc: "Own 250 total Team units.", flavor: "I don't care if it works. I want it." },
    groundhogDay: { name: "Groundhog Day", desc: "Perform 10 Promotions (resets).", flavor: "Again? Again. AGAIN." },
    quantumLeap: { desc: "Accumulate 50 Q-bits.", flavor: "Oh boy." },
    bugClicker: { desc: "Reach 100,000 manual clicks.", flavor: "A tribute to the grandfather of all clickers." },
    marioCastle: { name: "Our Princess Is in Another Castle!", desc: "Perform your first Promotion (reset).", flavor: "Thank you for playing! But now we start over." },
    oneUp: { desc: "Click 100 Golden Bugs.", flavor: "A hundred golden coins, one extra life." },
    bazinga: { desc: "Rack up 73 Million total bugs.", flavor: "73: the 21st prime, and the best number of all. Bazinga." },
    catchEmAll: { name: "Gotta Catch 'Em All!", desc: "Own 151 units of a single Team.", flavor: "There were only 151 of them, back in the day." },
    imagination: { desc: "Unlock 5 different skins.", flavor: "🌈 Im-ag-in-a-tion." },
    moneyMoneyMoney: { desc: "Earn 10 Billion lifetime bugs.", flavor: "Mr. Krabs smells money." },
    pazienteZero: { name: "Patient Zero", desc: "Reach 250,000 manual clicks.", flavor: "A click infected you. Now you are the infection." },
    rpdElite: { name: "R.P.D. Elite", desc: "Click 250 Golden Bugs.", flavor: "Espoon City Police. Freeze, bugs." },
    esposaUnlock: { name: "Till Code Do Us Part", desc: "Play for 24 hours total.", flavor: "A serious commitment. To code." },
    collezionista: { name: "Collector", desc: "Unlock 15 different skins.", flavor: "The party starts when you've got them all." }
};
