/* EN overlay — texts. Stessa struttura annidata di js/data/texts.js. */
window.gameData = window.gameData || {};
window.gameData.i18n = window.gameData.i18n || {};
window.gameData.i18n.en = window.gameData.i18n.en || {};
window.gameData.i18n.en.texts = {
    ui: {
        buy: "Buy",
        owned: "OWNED",
        max: "MAX",
        locked: "LOCKED",
        cost: "Cost",
        clickPower: "Click Power",
        bugsWallet: "Current Bugs",
        runScore: "Current Run Total",
        careerScore: "Career Total",
        offlineEarned: "Earned Offline",
        promoProgress: "Promotion Progress",
        equipped: "IN USE",
        useSkin: "USE SKIN",
        noToken: "NO TOKEN",
        skinLocked: "LOCKED",
        unknown: "???",
        secretGoal: "Secret Goal...",
        rewardClaim: "Claim",
        rewardDone: "Claimed",
        loadingData: "Loading data...",
        loadingAssets: "Loading assets...",
        systemStart: "Booting system...",
        loaderTips: [
            "Tip: click fast to multiply the bugs.",
            "Promotions unlock new mechanics.",
            "Open the Arcade for minigames and bonuses.",
            "Skins change your look and special effects.",
            "The Q-Lab unlocks after lots of promotions.",
            "Saving is automatic, straight to IndexedDB.",
            "The Golden Bug shows up at random: catch it!",
            "Espo Fury multiplies BPS x7 for a few seconds.",
            "More Bugs Per Second = faster promotions."
        ],
        promoReady: "READY!",
        promotionReadyTitle: "PROMOTION READY!",
        bugsTitle: "Bugs",
        furyActive: "BPS x7",
        furyCooldown: "Recharging...",
        furyReady: "ESPO FURY",
        clickMe: "CLICK!",
        labFull: "Lab fully staffed!",
        noItemsBuy: "Nothing to buy right now.",
        noItemsLock: "No locked items in sight.",
        noItemsPurchased: "No purchases made yet.",
        nothingToShow: "Nothing to show.",
        defaultPlayer: "Player",
        initPrivateAssets: "Initializing private assets...",
        readNews: "Read the update news",
        newsLabel: "What's New",
        newsLoadError: "Couldn't load the news.",
        audioOn: "Enable audio",
        audioOff: "Mute audio",
        introWelcome: "WELCOME"
    },
    toasts: {
        welcome: "Welcome",
        saved: "Save complete",
        saveError: "Error while saving",
        insufficientBugs: "Not enough bugs!",
        insufficientTokens: "Not enough Tokens!",
        skinBought: "Skin Purchased: {name}!",
        skinUnlock: "New Skin: {name}!",
        achievementUnlock: "🏆 Unlocked: {name}",
        rewardAvailable: " (Reward available!)",
        rewardClaimed: "Claimed: {message}",
        furyCalm: "Espo is calming down: {seconds}s",
        furyActive: "ESPO FURY ACTIVE — BPS x7",
        furyEnded: "Espo has calmed down.",
        promoSuccess: "Promotion complete! Nice work!",
        cloudSync: "Progress downloaded from the Cloud!",
        backupRestored: "Data restored from the safety Backup!",
        fileCorrupt: "Main file corrupted. Loaded Backup.",
        versionMismatch: "⚠️ Incompatible save version!",
        memoryFull: "Memory full! Can't save locally.",
        prestigeNeedMore: "You need to rack up more bugs to earn a promotion!",
        prestigeNeedComplete: "You must complete the project (100%) for the promotion!",
        bugCrit: "Critical Bug Fixed! +{amount} bugs!",
        offlineClaim: "You claimed {amount} bugs!",
        settingsSaved: "Preferences Saved",
        audioReset: "Audio reset to default values",
        passChanged: "Password Updated!",
        nameChanged: "Name Updated!",
        arcadeWelcome: "Welcome to the Server Room (Arcade)!",
        memoryWarn: "⚠️ Memory almost full",
        sessionExpired24h: "⏰ Session expired (24h). Log in again to save.",
        cloudConflict: "⚠️ Cloud conflict! Reload the page so you don't lose progress.",
        sessionReload: "⚠️ Session expired! Reload the page to save.",
        skinNeedFormat: "⚠️ You must perform at least 1 Format to unlock this skin!",
        luckyBug: "🍀 LUCKY BUG! +{amount} bugs!",
        frenzy: "⚡ FRENZY! Click ×7 for 15 seconds!",
        dailyBonus: "🎁 Daily bonus · Day {streak} · +{amount} bugs!",
        milestone: "🏆 {name}: {amount} units!"
    },
    dialogs: {
        logout: "Log out?",
        resetConfirm: "WARNING: This will reset all progress back to square one (Hard Reset). Lab tokens and Skins will be lost. Continue?",
        deleteConfirm: "ARE YOU SURE? This action is irreversible and will wipe everything.",
        audioResetConfirm: "Restore the recommended default volumes?",
        enterPass: "Enter the password in the critical area.",
        fillFields: "Fill in both fields.",
        confirmPass: "Confirm current password:",
        accountDeleted: "Account deleted. Goodbye!",
        progressReset: "Progress reset successfully."
    },
    reformat: {
        prep: "PREPARING FORMAT",
        loadingData: "Loading data...",
        restoring: "RESTORING UNIVERSE..."
    },
    system: {
        storageBlocked: '⚠️ Your browser is blocking local saving. Progress <strong>will not be saved</strong>. On Edge: <em>Settings → Privacy → Tracking prevention → turn off for this site</em>. On Safari: <em>turn off "Prevent cross-site tracking"</em>. '
    },
    leaderboard: {
        loading: "Loading...",
        empty: "No scores yet. Be the first!",
        error: "Couldn't load the leaderboard.",
        levelAbbr: "LVL",
        formatTitle: "Formats (NG+)"
    },
    stats: {
        promoProgress: "Promotion Progress",
        goal: "Goal:",
        economy: "Company Economy",
        bugsNow: "Current Bugs",
        runTotal: "Run Total",
        careerTotal: "Career Total",
        offline: "Offline",
        performance: "Performance & Tech",
        multiplier: "Multiplier",
        multiverse: "Multiverse (NG+)",
        universesDestroyed: "Universes Destroyed",
        quantumEnergy: "Quantum Energy",
        profile: "Profile & Visuals",
        playtime: "Play Time",
        totalClicks: "Total Clicks",
        comboRecord: "Best Combo",
        promotions: "Promotions"
    },
    v2: {
        title: "WELCOME TO V2.0",
        thanks: "Thanks for playing the first version of <b>Espo Clicker</b>!",
        intro: "To introduce <b>New Game+</b>, the Arcade and to rebalance the leaderboard, we performed a <b>Quantum Realignment</b> of the servers.",
        skinsSafe: "YOUR SKINS ARE SAFE",
        wardrobeIntact: "Your wardrobe is intact.",
        veteranBonus: "VETERAN BONUS",
        credited: "We've credited you <b>1 Format</b> and <b>1 Q-Bit</b>. The Quantum Lab is already open!",
        discover: "DISCOVER WHAT'S NEW"
    },
    format: {
        time: { d: "d", h: "h", m: "m", s: "s" }
    },
    rarities: {
        common: "COMMON", rare: "RARE", epic: "EPIC",
        legendary: "LEGENDARY", divine: "DIVINE", christmas: "FESTIVE"
    }
}
