/* EN overlay — upgrades (click/prestige/building/super). Stesse chiavi di js/data/upgrades.js. */
window.gameData = window.gameData || {};
window.gameData.i18n = window.gameData.i18n || {};
window.gameData.i18n.en = window.gameData.i18n.en || {};
window.gameData.i18n.en.clickUpgrades = {
    caffeForte: { name: "Strong Coffee", desc: "Adds +1 to the value of every click." },
    tastieraErgonomica: { name: "Ergonomic Keyboard", desc: "Adds +5 to the value of every click." },
    mouseGaming: { name: "Gaming Mouse", desc: "Adds +10 to the value of every click." },
    ergonomiaEstrema: { name: "Extreme Ergonomics", desc: "Adds +50 to the value of every click." },
    aiClick: { name: "Artificial Intelligence", desc: "Adds +500 to the value of every click." },
    doppioClick: { name: "Double Click", desc: "Doubles the base value of your clicks." },
    manoBionica: { name: "Bionic Hand", desc: "Every click also earns 1% of your BPS." },
    clickAutomatico: { name: "Auto Click", desc: "Adds BPS equal to your number of QA Assistants." },
    hacking: { name: "Ethical Hacking", desc: "Doubles the chance of finding Critical Tickets." },
    interfacciaNeurale: { name: "Neural Interface", desc: "Adds +2,000 to the value of every click." },
    overclockingCognitivo: { name: "Cognitive Overclocking", desc: "Triples the base value of your clicks." },
    clickDivino: { name: "Divine Click", desc: "The Bionic Hand now earns 2% of your BPS." }
};
window.gameData.i18n.en.prestigeUpgrades = {
    sinergia: { name: "Managerial Synergy", desc: "Each promotion point is worth +0.1% more (Cumulative)." },
    paracadute: { name: "Golden Parachute", desc: "Start the run with +2,000 Bugs per level." },
    serverAlwaysOn: { name: "Server Always-On", desc: "Raises offline earnings from 30% to 100% (+10%/lvl)." },
    contrattazione: { name: "Negotiation", desc: "Reduces the cost growth of Teams (Scaling)." },
    eredita: { name: "Structural Legacy", desc: "Keep 1 \"QA Assistant\" per level after promotion." },
    outsourcing: { name: "Outsourcing", desc: "Reduces base costs by 5% per level." },
    accelerazione: { name: "Acceleration", desc: "Start with +1 QA Assistant." },
    crunchTime: { desc: "Active Ability: Espo flies into a rage! BPS x7 for 30s." },
    bugBounty: { name: "Bug Bounty", desc: "Critical Tickets (Golden Bug) are worth +20% more per level." },
    ticketPremium: { name: "Ticket Premium", desc: "Critical Tickets appear 2x as often." },
    reteContatti: { name: "Contact Network", desc: "Reduces the ESPO FURY cooldown by 30s per level." },
    esperienzaAccumulata: { name: "Accumulated Experience", desc: "Raises click value by +2% per level (permanent)." },
    deadlineStretta: { name: "Tight Deadline", desc: "keepTeams keeps +1 extra level for each purchase." }
};
window.gameData.i18n.en.buildingEnhancements = {
    caffeDoppio: { name: "Double Coffee", desc: "QA Assistants x2 BPS." },
    caffeTriplo: { name: "Triple Coffee", desc: "QA Assistants x2 BPS." },
    scrivanieErgonomiche: { name: "Ergonomic Desks", desc: "QA Assistants x3 BPS." },
    formazioneAvanzata: { name: "Advanced Training", desc: "QA Assistants x3 BPS." },
    managerJunior: { name: "Junior Manager", desc: "QA Assistants x4 BPS." },
    jiraAI: { desc: "Jira Ticket x2 BPS." },
    jiraCloud: { desc: "Jira Ticket x2 BPS." },
    jiraDataCenter: { desc: "Jira Ticket x3 BPS." },
    jiraPremium: { desc: "Jira Ticket x3 BPS." },
    jiraSelfHealing: { desc: "Jira Ticket x4 BPS." },
    scrum: { name: "Scrum Methodology", desc: "QA Team x2 BPS." },
    teamLeader: { desc: "QA Team x2 BPS." },
    certificazioneISTQB: { name: "ISTQB Certification", desc: "QA Team x3 BPS." },
    bonusProduttivita: { name: "Productivity Bonus", desc: "QA Team x3 BPS." },
    teamGlobale: { name: "Global Team 24/7", desc: "QA Team x4 BPS." },
    selenium: { name: "Selenium Framework", desc: "Automation x2 BPS." },
    cucumber: { desc: "Automation x2 BPS." },
    ciCd: { name: "CI/CD Pipeline", desc: "Automation x3 BPS." },
    docker: { name: "Docker Container", desc: "Automation x3 BPS." },
    kubernetes: { name: "Kubernetes Orchestration", desc: "Automation x4 BPS." },
    kanban: { name: "Kanban Board", desc: "Agile Methodology x2 BPS." },
    safe: { name: "SAFe Framework", desc: "Agile Methodology x2 BPS." },
    productOwner: { name: "Dedicated Product Owner", desc: "Agile Methodology x3 BPS." },
    releaseTrain: { desc: "Agile Methodology x3 BPS." },
    devOps: { name: "DevOps Culture", desc: "Agile Methodology x4 BPS." },
    deepLearning: { desc: "AI Debugger x2 BPS." },
    machineLearning: { desc: "AI Debugger x2 BPS." },
    retiNeurali: { name: "Neural Networks", desc: "AI Debugger x3 BPS." },
    quantumComputing: { desc: "AI Debugger x3 BPS." },
    skynet: { desc: "AI Debugger x4 BPS." },
    entanglementLink: { desc: "Quantum Server x2 BPS." },
    superpositionCores: { desc: "Quantum Server x2 BPS." },
    errorCorrection: { desc: "Quantum Server x3 BPS." },
    quantumSupremacy: { name: "Quantum Supremacy", desc: "Quantum Server x4 BPS." },
    subspaceTransceiver: { desc: "Galactic Network x2 BPS." },
    dysonNodes: { name: "Dyson Nodes", desc: "Galactic Network x2 BPS." },
    wormholeRouting: { desc: "Galactic Network x3 BPS." },
    federazioneGalattica: { name: "Galactic Federation", desc: "Galactic Network x4 BPS." },
    paradoxPrevention: { desc: "Temporal Debug x2 BPS." },
    timelineBranching: { desc: "Temporal Debug x2 BPS." },
    chronosTrigger: { desc: "Temporal Debug x3 BPS." },
    immutablePast: { name: "Immutable Past", desc: "Temporal Debug x4 BPS." },
    coscienzaCollettiva: { name: "Collective Quantum Consciousness", desc: "Quantum Server x4 BPS." },
    menteUniverso: { name: "Mind of the Universe", desc: "Galactic Network x4 BPS." },
    eternitaParallela: { name: "Parallel Eternity", desc: "Temporal Debug x4 BPS." },
    menteDivisa: { name: "Divided Mind", desc: "Conscious Singularity x2 BPS." },
    neuroniFotonici: { name: "Photonic Neurons", desc: "Conscious Singularity x2 BPS." },
    singolaRete: { name: "Single Network", desc: "Conscious Singularity x3 BPS." },
    overmindProtocol: { desc: "Conscious Singularity x3 BPS." },
    coscienzaAssoluta: { name: "Absolute Consciousness", desc: "Conscious Singularity x4 BPS." },
    frameworkRealta: { name: "Reality Framework", desc: "Architecture of Infinity x2 BPS." },
    compilatoreUniversale: { name: "Universal Compiler", desc: "Architecture of Infinity x2 BPS." },
    patchEsistenziale: { name: "Existential Patch", desc: "Architecture of Infinity x3 BPS." },
    hotfixDivino: { name: "Divine Hotfix", desc: "Architecture of Infinity x3 BPS." },
    deployDelCosmo: { name: "Deploy of the Cosmos", desc: "Architecture of Infinity x4 BPS." }
};
window.gameData.i18n.en.superUpgrades = {
    risveglio: { name: "Quantum Awakening", desc: "Awareness of the multiverse doubles (x2) the base power of all your clicks forever." },
    fastStart: { name: "Fast Start", desc: "Begin every Universe with +1 Million Bugs and 5 QA Assistants." },
    goldenAura: { name: "Golden Aura", desc: "Quantum resonance makes Critical Tickets (Golden Bug) contain triple (x3) the Bugs." },
    qDiscount: { name: "Data Compression", desc: "All Lab upgrades cost 15% less." },
    tokenDuplicator: { name: "Token Replicator", desc: "The machine extracts an extra 20% Lab Tokens on every Promotion." },
    keepTeams: { name: "Memory Persistence", desc: "Keep the first 5 levels of the BASE Teams (Assistant, Ticket, QA) after a Promotion." },
    overclock: { name: "Overclock", desc: "ESPO FURY lasts 60 seconds instead of 30." },
    risonanzaAurea: { name: "Golden Resonance", desc: "Golden Bug appears every 45s instead of 60s (base)." },
    echoQuantico: { name: "Quantum Echo", desc: "Each Format keeps 1 prestige upgrade you've already purchased." }
};
